project:
  type: website
  output-dir: docs

website:
  title: CMR-verse
  page-footer: A quantitative appraisal of CMR publications - G. Bisaccia
  navbar:
    logo: logo.jpg
    left:
      - icon: github
        href: https://htahackathon2024.github.io/HERA
      - href: index.qmd
        text: Home
      - href: getstarted.qmd
        text: Get Started

reader-mode: false
format:
  html:
    theme: 
      light: [litera]
      dark: [superhero]
    toc: true
    toc-location: left