project:
  type: website
  output-dir: docs

website:
  title: CMR-verse
  page-footer: A quantitative appraisal of CMR publications - G. Bisaccia
  navbar:
    #logo: 
    left:
      - icon: github
        href: https://github.com/bisacciamd/CMR-verse/
      - href: index.qmd
        text: Home
      - href: index.qmd
        text: The CMR-verse

reader-mode: false
format:
  html:
    theme: 
      light: [litera]
      dark: [superhero]
    toc: true
    toc-location: left